services:
  web-estudio-marini:
    container_name: web_estudio_marini
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      # Esto hace que el contenedor escuche tus cambios en vivo
      - .:/app
      - /app/node_modules